package com.operativus.agentmanager.control.service.scoring;

import com.operativus.agentmanager.core.entity.EvaluationCase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

/**
 * Domain Responsibility: Evaluates Agent outputs by prompting an LLM to act as an impartial judge based on given constraints.
 * State: Stateless
 * Dependencies: ChatClient
 */
@Component
public class LlmJudgeScorer implements Scorer {

    private static final Logger log = LoggerFactory.getLogger(LlmJudgeScorer.class);

    private final ChatClient chatClient;
    
    // We use a predefined structured output to force the LLM judge to respond 
    // deterministically and consistently.
    public record JudgeResponse(double score, boolean passed, String reasoning) {}

    /**
     * @summary Initializes the LLM Judge with a strict, impartial system prompt.
     * @logic
     * - Configures the `ChatClient` with a highly specific system prompt designed to grade outputs consistently.
     */
    public LlmJudgeScorer(ChatClient.Builder chatClientBuilder) {
        // Build a client specifically for judging. We might want a stronger/cheaper model depending on configuration.
        this.chatClient = chatClientBuilder
                .defaultSystem("""
                        You are an impartial, strict, and precise expert evaluator grading the output of an AI agent.
                        You will be provided with:
                        1. The original Input/Question.
                        2. The Expected Criteria / Constraints.
                        3. The Actual Output generated by the agent.
                        
                        Your goal is to evaluate if the actual output meets the expected criteria based on the input.
                        Score the response from 0.0 (Complete Failure) to 1.0 (Perfect Response).
                        A score of 0.8 or higher is generally considered passing unless constraints are completely missed.
                        
                        Do not hallucinate facts. Do not be overly lenient.
                        """)
                .build();
    }

    /**
     * @summary Scores an evaluation case by querying an LLM to act as a judge.
     * @logic
     * - Validates actual output is non-empty.
     * - Initializes a Spring AI BeanOutputConverter expecting a `JudgeResponse` record.
     * - Constructs a prompt providing the Input, Expected Criteria, and Actual Output.
     * - Calls the LLM and requests structured JSON output.
     * - Parses the response and extracts the numerical score, pass/fail status, and LLM reasoning.
     */
    @Override
    public ScorerResult evaluate(EvaluationCase evaluationCase, String actualOutput) {
        if (!StringUtils.hasText(actualOutput)) {
            return new ScorerResult(0.0, false, "Actual output was empty.");
        }

        try {
            String promptTemplate = """
                    Input/Question:
                    {input}
                    
                    Expected Criteria:
                    {expected}
                    
                    Actual Output:
                    {actual}
                    
                    Evaluate the output and provide your score, pass/fail status, and a brief reasoning.
                    """;

            JudgeResponse judgeResponse = chatClient.prompt()
                    .user(userSpec -> userSpec
                            .text(promptTemplate)
                            .param("input", evaluationCase.getInput())
                            .param("expected", evaluationCase.getExpectedOutput() != null ? evaluationCase.getExpectedOutput() : "Provide a helpful, accurate, and reasonably short response.")
                            .param("actual", actualOutput)
                    )
                    .call()
                    .entity(JudgeResponse.class);

            if (judgeResponse != null) {
                 return new ScorerResult(judgeResponse.score(), judgeResponse.passed(), judgeResponse.reasoning());
            }
            // Bug #42 diagnostic: when the judge returns a non-throwing-but-null structured
            // response, every eval row would silently land as score=0.0 with no log trace.
            // Log a warning so operators can correlate it with provider/model issues.
            log.warn("LlmJudgeScorer: judge model returned null structured response for case '{}' (provider/model misconfigured or schema-non-conformant output). Recording score=0.0.",
                    evaluationCase.getId());
            return new ScorerResult(0.0, false, "Judge model failed to return a valid structured evaluation.");

        } catch (Exception e) {
            // Bug #42 diagnostic: previously this swallowed the exception and stored
            // only the message on EvaluationResult.errorMessage. Surface a WARN-level log
            // so persistent score=0.0 patterns can be root-caused from /private/tmp/agm-backend.log
            // without scraping the database.
            log.warn("LlmJudgeScorer: evaluation failed for case '{}': {}. Recording score=0.0.",
                    evaluationCase.getId(), e.getMessage(), e);
            return new ScorerResult(0.0, false, "LLM Judge evaluation failed: " + e.getMessage());
        }
    }
}
