--liquibase formatted sql

--changeset agm:059-schedule-runs-workflow-run-id
-- Persist the workflow_run_id generated by executeWorkflowAsync onto the schedule_runs row
-- so the poller can back-propagate terminal workflow status (COMPLETED/FAILED/CANCELLED)
-- to the parent schedule_run instead of stamping COMPLETED at dispatch time.
-- Only WORKFLOW-target schedule_runs will have this column populated; all others remain NULL.
ALTER TABLE schedule_runs ADD COLUMN workflow_run_id VARCHAR(255);
CREATE INDEX idx_schedule_runs_workflow_run_id ON schedule_runs (workflow_run_id) WHERE workflow_run_id IS NOT NULL;
--rollback DROP INDEX idx_schedule_runs_workflow_run_id; ALTER TABLE schedule_runs DROP COLUMN workflow_run_id;
